  media:
  - name: files
    label: Files
    input: files/documents
    output: /files/documents
    categories: [ document ]
  - name: images
    label: Images
    input: assets/img
    output: /assets/img
    extensions: [ jpg, png, webp, svg ]